// ==========================================================================
// 📖 课文与字词矩阵数据（按词组单位：全拼音与双语翻译无死角覆盖） - data.js
// ==========================================================================

const lessonTitle = "深夜的黑油漆";

const lessonData = [
    // --- 第1段 ---
    ["繁华", "fán huá", "prosperous / bustling", "pesat / meriah / sibuk"],
    ["都市的", "dū shì de", "city's / metropolis's", "kota raya punya"],
    ["边缘，", "biān yuán", "edge / margin / periphery", "pinggir / sempadan"],
    ["是一片", "shì yí piàn", "is a stretch of", "merupakan sekawasan"],
    ["疏疏落落的", "shū shū luò luò de", "scattered / sparse", "yang jarang-jarang / bertaburan"],
    ["旧住宅区。", "jiù zhù zhái qū", "old residential area", "kawasan perumahan lama"],
    ["单亲", "dān qīn", "single parent", "ibu/bapa tunggal"],
    ["妈妈", "mā ma", "mother", "ibu"],
    ["阿珍", "ā zhēn", "Azhen (name)", "Azhen"],
    ["在这里", "zài zhè lǐ", "here", "di sini"],
    ["开着一间", "kāi zhe yì jiān", "opening a shop", "membuka sebuah"],
    ["维持生计的", "wéi chí shēng jì de", "making a living / earn a livelihood", "menyara hidup punya / mencari rezeki"],
    ["小杂货店。", "xiǎo zá huò diàn", "small grocery store / sundry shop", "kedai runcit kecil"],
    ["为了让", "wèi le ràng", "in order to make", "demi membiarkan"],
    ["破旧的", "pò jiù de", "shabby / worn-out", "yang usang / buruk"],
    ["店面", "diàn miàn", "shopfront", "muka kedai"],
    ["显得", "xiǎn de", "look / appear", "kelihatan / nampak"],
    ["体面些，", "tǐ miàn xiē", "decent / respectable / dignified", "bermaruah / senonoh / ada kelas"],
    ["她不久前", "tā bù jiǔ qián", "she not long ago", "dia tidak lama dahulu"],
    ["刚把", "gāng bǎ", "just (object marker)", "baru sahaja (penanda objek)"],
    ["杂货店的", "zá huò diàn de", "grocery store's", "kedai runcit punya"],
    ["铁卷门", "tiě juǎn mén", "rolling iron shutter door", "pintu besi gulung / pintu jeruji"],
    ["刷上了", "shuā shàng le", "painted on", "mengecat naik"],
    ["雪白的", "xuě bái de", "snow-white", "yang putih melepak / putih salji"],
    ["油漆。", "yóu qī", "paint", "cat"],
    ["四季", "sì jì", "four seasons", "empat musim"],
    ["风景如画的", "fēng jǐng rú huà de", "picturesque scenery", "pemandangan indah bagai lukisan punya"],
    ["季节里，", "jì jié lǐ", "in the season", "dalam musim"],
    ["这扇", "zhè shàn", "this (classifier for doors/windows)", "pintu... ini"],
    ["白门", "bái mén", "white door", "pintu putih"],
    ["成了", "chéng le", "became", "menjadi"],
    ["街角", "jiē jiǎo", "street corner", "penjuru jalan / sudut jalan"],
    ["唯一的", "wéi yī de", "only / sole", "satu-satunya"],
    ["亮色。", "liàng sè", "bright color / highlight", "warna yang cerah / tarikan"],
    ["\n", "", "", ""],

    // --- 第2段 ---
    ["谁知，", "shéi zhī", "who would have thought / unexpectedly", "siapa sangka / tidak diduga"],
    ["一个", "yí gè", "a", "sebuah / seorang"],
    ["深冬的", "shēn dōng de", "of mid-winter", "musim sejuk yang dalam punya"],
    ["深夜，", "shēn yè", "late at night", "larut malam"],
    ["寒风", "hán fēng", "chilling wind / cold wind", "angin sejuk / bayu dingin"],
    ["如刀子般", "rú dāo zi bān", "like a knife", "seperti pisau / bagai sembilu"],
    ["刮过。", "guā guò", "blew across / swept through", "bertiup melepasi / melanda"],
    ["第二天", "dì èr tiān", "the next day", "hari keesokan"],
    ["清晨", "qīng chén", "early morning", "awal pagi"],
    ["阿珍", "ā zhēn", "Azhen", "Azhen"],
    ["开门时，", "kāi mén shí", "when opening the door", "apabila membuka pintu"],
    ["却", "què", "however / but", "namun / tetapi"],
    ["惊得", "jīng de", "so shocked that", "terkejut sehinggakan"],
    ["魂飞魄散——", "hún fēi pò sàn", "frightened out of wits / terrified", "terperanjat besar / ketakutan setengah mati"],
    ["雪白的", "xuě bái de", "snow-white", "yang putih melepak"],
    ["铁卷门上，", "tiě juǎn mén shàng", "on the rolling iron door", "di atas pintu besi gulung"],
    ["被人用", "bèi rén yòng", "by someone using", "oleh orang menggunakan"],
    ["黏稠的", "nián chóu de", "thick / viscous / sticky", "yang pekat melekit / likat"],
    ["黑油漆", "hēi yóu qī", "black paint", "cat hitam"],
    ["恶作剧般地", "è zuò jù bān dì", "mischievously / like a prank", "seperti prank / nakal / gurauan melampau"],
    ["涂鸦了", "tú yā le", "graffitied / scribbled", "menconteng / membuat grafiti"],
    ["一只", "yì zhī", "a (classifier for insects/birds)", "seekor"],
    ["极其", "jí qí", "extremely", "amat / sangat"],
    ["丑陋的", "chǒu lòu de", "ugly", "yang hodoh / buruk rupa"],
    ["大蜘蛛，", "dà zhī zhū", "big spider", "labah-labah besar"],
    ["黑亮的", "hēi liàng de", "shiny black", "hitam berkilat"],
    ["油漆", "yóu qī", "paint", "cat"],
    ["顺着", "shùn zhe", "along / down along", "mengikut / turun mengalir"],
    ["白门", "bái mén", "the white door", "pintu putih"],
    ["往下淌，", "wǎng xià tǎng", "dripping down / trickling down", "mengalir turun ke bawah"],
    ["显得", "xiǎn de", "appeared / looked", "kelihatan / nampak"],
    ["格格不入、", "gé gé bú rù", "out of place / incompatible", "janggal / tidak sepadan"],
    ["狼藉一片。", "láng jí yí piàn", "in a total mess / scattered chaos", "berserak-serak / kucar-kacir sama sekali"],
    ["阿珍的", "ā zhēn de", "Azhen's", "Azhen punya"],
    ["心头一紧，", "hān tou yì jǐn", "heart tightened / felt a pang", "hati menjadi sebak / tersentuh"],
    ["所有的", "suǒ yǒu de", "all the", "kesemua"],
    ["惊讶、", "jīng yà", "surprise / astonishment", "perasaan terkejut"],
    ["愤怒", "fèn nù", "anger / rage", "kemarahan / amarah"],
    ["与", "yǔ", "and", "dan"],
    ["无奈", "wú nài", "helplessness", "kekecewaan / ketidakupayaan"],
    ["渐渐", "jiàn jiàn", "gradually", "beransur-ansur / perlahan-lahan"],
    ["涌上心头。", "yǒng shàng xīn tóu", "welled up in the heart", "meluap ke hulu hati"],
    ["读书", "dú shū", "studying", "belajar"],
    ["耗费", "hào fèi", "consumed / wasted", "memeras / menghabiskan"],
    ["心智的", "hān zhì de", "mental energy / mind", "minda / mental punya"],
    ["女儿", "nǚ ér", "daughter", "anak perempuan"],
    ["安慰她，", "ān wèi tā", "comforted her", "menenanginya / memujuknya"],
    ["阿珍", "ā zhēn", "Azhen", "Azhen"],
    ["却", "què", "however", "namun"],
    ["打定", "dǎ dìng", "made up mind", "menetapkan hati"],
    ["不到黄河心不死", "bú dào huáng hé xīn bù sǐ", "not stop until reaching the limit / completely determined", "tidak akan menyerah kalah selagi belum sampai ke penghujungnya"],
    ["的主意，", "de zhǔ yi", "idea / decision", "keputusan / tekad"],
    ["咬了刮牙，", "yǎo le yǎo yá", "grit teeth", "mengetap gigi / kuatkan semangat"],
    ["决定", "jué dìng", "decided", "memutuskan"],
    ["今晚", "jīn wǎn", "tonight", "malam ini"],
    ["横竖", "héng shù", "anyway / in any case", "apa-apa pun / walau bagaimanapun"],
    ["不睡，", "bú shuì", "not sleeping", "tidak tidur"],
    ["躲在", "duǒ zài", "hiding in", "bersembunyi di"],
    ["暗处", "àn chù", "dark place / hidden place", "tempat gelap / tersorok"],
    ["捉住", "zhuō zhù", "catch / capture", "menangkap / mencekat"],
    ["这个", "zhè gè", "this", "budak... ini"],
    ["别有用心的", "bié yǒu yòng xīn de", "having ulterior motives", "mempunyai agenda tersembunyi punya"],
    ["“恶作剧者”！", "è zuò jù zhě", "prankster / mischief-maker", "pelaku prank / orang nakal"],
    ["\n", "", "", ""],

    // --- 第3段 ---
    ["凌晨", "líng chén", "before dawn / early morning hours", "awal pagi / subuh"],
    ["两点，", "liǎng diǎn", "two o'clock", "pukul dua"],
    ["街头", "jiē tóu", "street", "jalanan"],
    ["尘嚣", "chén xiāo", "hubbub / clamor of the world", "hiruk-pikuk dunia / kekotoran"],
    ["尽散。", "jìn sàn", "all dissipated / cleared", "kesemuanya hilang / bersurai"],
    ["一盏", "yì zhǎn", "a (classifier for lamps)", "sebuah"],
    ["昏黄的", "hūn huáng de", "dim yellow", "yang kuning suram / malap"],
    ["灯光下，", "dēng guāng xià", "under the lamplight", "di bawah cahaya lampu"],
    ["一个", "yí gè", "a", "seorang"],
    ["有些", "yǒu xiē", "somewhat / a bit", "agak / sedikit"],
    ["嗫嚅、", "niè rú", "hesitating in speech", "teragap-agap / ragu-ragu"],
    ["怯懦的", "qiè nuò de", "timid / cowardly", "penakut / segan punya"],
    ["身影", "shēng yǐng", "figure / silhouette", "kelibat / susuk tubuh"],
    ["贼一样地", "zé yí yàng dì", "like a thief", "seperti seorang pencuri"],
    ["潜回", "qián huí", "sneaked into / slipped back", "menyelinap masuk ke"],
    ["过来。", "guò lái", "over", "mari."],
    ["那是一个", "nà shì yí gè", "that was a", "ia merupakan seorang"],
    ["穿着", "chuān zhe", "wearing", "memakai"],
    ["破旧", "pò jiù", "shabby / worn-out", "usang / buruk"],
    ["夹克衫、", "jiá kè shān", "jacket", "jaket"],
    ["长满", "zhǎng mǎn", "covered with / full of", "penuh dengan"],
    ["老茧的", "lǎo jiǎn de", "calloused", "kapal / kematu punya"],
    ["手里", "shǒu lǐ", "hand inside", "dalam tangan"],
    ["提着", "tí zhe", "carrying", "menjinjing"],
    ["油漆罐的", "yóu qī guàn de", "paint can", "tin cat punya"],
    ["流浪儿。", "liú làng ér", "street urchin / homeless child / stray kid", "anak gelandangan / anak jalanan"],
    ["他", "tā", "he", "dia"],
    ["眼里", "yǎn lǐ", "in the eyes", "di dalam mata"],
    ["闪过一丝", "shǎn guò yì sī", "flashed a trace of", "terbayang seberkas / sekelip"],
    ["狠戾，", "hěn lì", "ruthlessness / ferocity", "kekejaman / niat jahat"],
    ["正", "zhèng", "right now", "sedang"],
    ["准备", "zhǔn bèi", "preparing to / ready to", "bersedia"],
    ["再次", "zài cì", "once again", "sekali lagi"],
    ["妄动，", "wàng dòng", "act recklessly / cause damage", "bertindak liar / merosakkan"],
    ["大口大口地", "dà kǒu dà kǒu dì", "in huge mouthfuls / massively", "secara besar-besaran / banyak"],
    ["往墙上", "wǎng qiáng shàng", "onto the wall", "ke atas dinding"],
    ["泼洒", "pō sǎ", "splash / spill", "menyimbah / memercik"],
    ["黑漆。", "hēi qī", "black paint", "cat hitam."],
    ["\n", "", "", ""],

    // --- 第4段 ---
    ["躲在", "duǒ zài", "hiding inside", "bersembunyi di"],
    ["门后的", "mén hòu de", "behind the door", "belakang pintu punya"],
    ["阿珍", "ā zhēn", "Azhen", "Azhen"],
    ["刚想", "gāng xiǎng", "just wanted to", "baru berniat mahu"],
    ["一跃而起", "yí y躍 ér qǐ", "leap up / jump up quickly", "melompat bangun"],
    ["飞快地", "fēi kuài dì", "swiftly / fast", "dengan pantas"],
    ["闩住他，", "shuān zhù tā", "bolt him / catch and trap him", "menangkap dan menyekatnya"],
    ["可不知怎地，", "kě bù zhī zěn de", "but somehow / don't know why", "namun tidak tahu mengapa"],
    ["细细看去，", "xì xì kàn qù", "looking closely", "melihat dengan teliti"],
    ["借着", "jiè zhe", "by means of / under cover of", "dengan bantuan / mengambil kesempatan"],
    ["昏黄的", "hūn huáng de", "dim yellow", "yang kuning suram / malap"],
    ["月光，", "yuè guāng", "moonlight", "cahaya bulan"],
    ["她看到", "tā kàn dào", "she saw", "dia melihat"],
    ["男孩", "nán hái", "the boy", "budak lelaki itu"],
    ["那双", "nà shuāng", "that pair of", "sepasang"],
    ["凹陷下去的", "āo xiàn xià qù de", "sunken / hollowed", "yang cengkung / terperosok ke dalam"],
    ["眼睛里", "yǎn jing lǐ", "inside the eyes", "mata di dalam"],
    ["闪动着", "shǎn dòng zhe", "flickering with", "memancarkan / berkelip"],
    ["无家的", "wú jiā de", "homeless", "yang tiada rumah / gelandangan"],
    ["孤独", "gū dú", "loneliness / solitary", "kesunyian / kesorangan"],
    ["与", "yǔ", "and", "dan"],
    ["卑微的", "bēi wēi de", "humble / low status", "rendah diri / kerdil / hina punya"],
    ["乞求。", "qǐ qiú", "pleading / begging", "rayuan / permohonan."],
    ["阿珍", "ā zhēn", "Azhen", "Azhen"],
    ["狂跳不止的", "kuáng tiào bù zhǐ de", "wildly beating", "jantung yang berdegup kencang punya"],
    ["心", "xīn", "heart", "jantung / hati"],
    ["慢慢", "màn màn", "slowly", "perlahan-lahan"],
    ["平静下来，", "píng jìng xià lái", "calmed down", "berasa tenang semula"],
    ["两行", "liǎng háng", "two lines", "dua titisan"],
    ["温热的泪水", "wēn rè de lèi shuǐ", "warm tears", "air mata yang hangat"],
    ["却", "què", "however", "namun"],
    ["无声无息地", "wú shēng wú xī dì", "silently / without a sound", "tanpa sebarang bunyi"],
    ["淌下来。", "tǎng xià lái", "streamed down / trickled", "mengalir turun."],
    ["她", "tā", "she", "dia"],
    ["看穿了", "kàn chuān le", "saw through", "nampak jelas / faham"],
    ["这孩子", "zhè hái zi", "this child", "budak ini punya"],
    ["孤苦伶仃的", "gū kǔ líng dīng de", "solitary and helpless", "sebatang kara / keseorangan dan daif punya"],
    ["身世，", "shēn shì", "life experience / hard background", "latar belakang hidup / nasib diri"],
    ["明白", "míng bai", "understood / knew", "faham / tahu"],
    ["他用", "tā yòng", "he using", "dia menggunakan"],
    ["黑漆", "hēi qī", "black paint", "cat hitam"],
    ["涂鸦，", "tú yā", "graffiti / scribble", "menconteng"],
    ["不过是", "bú guò shì", "is just / merely", "hanyalah / cuma"],
    ["想吸引", "xiǎng xī yǐn", "want to attract", "mahu menarik"],
    ["这个", "zhè gè", "this", "dunia... ini"],
    ["冷漠", "lěng mò", "cold / indifferent", "dingin / tidak peduli / kejam"],
    ["世界的", "shì jiè de", "world's", "dunia punya"],
    ["注意罢了。", "zhù yì bà le", "attention only", "perhatian sahaja."],
    ["\n", "", "", ""],

    // --- 第5段 ---
    ["阿珍", "ā zhēn", "Azhen", "Azhen"],
    ["没有", "méi yǒu", "did not", "tidak"],
    ["当场揭穿、", "dāng chǎng jiē chuān", "exposed on the spot", "dibongkar di situ juga"],
    ["扭送他", "niǔ sòng tā", "escorted him / dragged him", "menangkap dan menyerahkannya"],
    ["去", "qù", "to", "ke"],
    ["派出所，", "pài chū suǒ", "police station", "balai polis"],
    ["而是", "ér shì", "but rather", "tetapi melainkan"],
    ["悄悄地", "qiāo qiāo dì", "quietly", "dengan senyap / sembunyi"],
    ["离开了", "lí kāi le", "left", "meninggalkan"],
    ["那扇", "nà shàn", "that", "pintu... itu"],
    ["大门。", "dà mén", "big door / shutter door", "pintu besar."],
    ["\n", "", "", ""],

    // --- 第6段 ---
    ["第二天", "dì èr tiān", "the next day", "hari keesokan"],
    ["清晨，", "qīng chén", "early morning", "awal pagi"],
    ["流浪儿", "liú làng ér", "stray child / street kid", "anak gelandangan / kutu jalanan"],
    ["再次", "zài cì", "once again", "sekali lagi"],
    ["走过", "zǒu guò", "walked past", "melangkah melepasi"],
    ["街角，", "jiē jiǎo", "street corner", "penjuru jalan"],
    ["准备", "zhǔn bèi", "preparing to / planning to", "bersedia / berniat"],
    ["来看看", "lái kàn kàn", "come to see", "datang untuk melihat"],
    ["阿珍", "ā zhēn", "Azhen", "Azhen punya"],
    ["愤怒", "fèn nù", "angry / raging", "kemarahan"],
    ["绝望的", "jué wàng de", "desperate / hopeless", "kekecewaan / ketiadaan harapan punya"],
    ["表情。", "biǎo qíng", "expression / riak wajah", "riak wajah / ekspresi muka."],
    ["可当他", "kě dāng tā", "but when he", "namun apabila dia"],
    ["经过", "jīng guò", "passed by", "melepasi / lalu di"],
    ["铁门时，", "tiě juǎn mén shí", "the iron door", "pintu besi gulung时"],
    ["却", "què", "however", "namun"],
    ["目瞪口呆地", "mù dèng kǒu dāi dì", "dumbfounded / gaped in shock", "tercengang / melongo lidah"],
    ["惊住了——", "jīng zhù le", "stunned / shocked", "terkejut besar / terpaku"],
    ["铁门旁，", "tiě mén páng", "beside the iron door", "di sebelah pintu besi"],
    ["没有", "méi yǒu", "there was no", "tidak ada"],
    ["报警的", "bào jǐng de", "reporting to police / police-calling", "yang melaporkan balai polis"],
    ["警察，", "jǐng chá", "police", "polis"],
    ["而是", "ér shì", "but rather", "tetapi melainkan"],
    ["整整齐齐地", "zhěng zhěng qí qí dì", "neatly / tidily", "dengan sangat rapi / tersusun"],
    ["摆着", "bǎi zhe", "placing / displaying", "terletak / diletakkan"],
    ["一桶", "yì tǒng", "a bucket of", "setong"],
    ["崭新的", "zhǎn xīn de", "brand new", "yang serba baru"],
    ["白油漆、", "bái yóu qī", "white paint", "cat putih"],
    ["一把", "yì bǎ", "a (classifier for brushes/knives)", "sebilang / sebuah"],
    ["刷子，", "shuā zi", "brush", "berus mengecat"],
    ["还有", "hái yǒu", "and also / as well as", "dan juga ada / serta"],
    ["一盒", "yì hé", "a box of", "sekotak"],
    ["热气腾腾、", "rè qì téng téng de", "piping hot", "panas berasap"],
    ["散发着", "sàn fā zhe", "emitting / sending out fragrance", "yang memancarkan / mengeluarkan haruman"],
    ["暗香的", "àn xiāng de", "subtle fragrance", "haruman yang lembut / wangi punya"],
    ["甜饼。", "tián bǐng", "cookies / sweet biscuits", "biskut manis / kuih."],
    ["白漆桶上", "bái qī tǒng shàng", "on the white paint bucket", "di atas tong cat putih"],
    ["贴着", "tiē zhe", "sticking with", "tertampal"],
    ["一张纸条，", "yì zhāng zhǐ tiáo", "a slip of paper / note", "sekeping nota / kertas kecil"],
    ["字迹", "zì jì", "handwriting", "tulisan tangan"],
    ["出奇地", "chū qí dì", "surprisingly / unusually", "secara luar biasa / aneh sekali"],
    ["平静", "píng jìn", "calm / peaceful", "tenang"],
    ["和", "hé", "and", "dan"],
    ["诚恳：", "chéng kěn", "sincere", "ikhlas / tulus:"],
    ["“孩子，", "hái zi", "Child,", "Wahai anakku,"],
    ["如果你", "nǐ rú guǒ", "if you", "sekiranya kamu"],
    ["喜欢", "xǐ huan", "like / love", "gemar / suka"],
    ["画画，", "huà huà", "drawing / painting", "melukis / melakar gambar"],
    ["这桶", "zhè tǒng", "this bucket", "tong... ini"],
    ["白漆", "bái qī", "white paint", "cat putih"],
    ["和", "hé", "and", "dan"],
    ["甜饼", "tián bǐng", "cookies", "biskut manis"],
    ["送给你。", "sòng gěi nǐ", "give to you as a gift", "hadiahkan kepada kamu."],
    ["但这扇门", "dàn zhè shàn mén", "but this door", "tetapi pintu... ini"],
    ["是阿姨", "shì ā yí", "is aunt's", "ialah makcik punya"],
    ["唯一的", "wéi yī de", "only", "satu-satunya"],
    ["救命稻草，", "jiù mìng dào cǎo", "lifesaver / life-saving straw", "talian hayat / jerami penyelamat"],
    ["请帮我", "qǐng bāng wǒ", "please help me", "tolong bantu saya"],
    ["把它", "bǎ tā", "take it (object marker)", "ia (penanda objek)"],
    ["刷回", "shuā huí", "paint back", "cat semula menjadi"],
    ["原本的", "yuán lái de", "original", "asalnya punya"],
    ["纯洁，", "chún jié", "purity / cleanness", "suci / bersih / putih"],
    ["好吗？”", "hǎo ma", "OK?", "boleh kan?”"],
    ["\n", "", "", ""],

    // --- 第7段 ---
    ["看到", "kàn dào", "seeing", "melihat"],
    ["这番话，", "zhè fān huà", "this speech / note words", "nota kata-kata ini"],
    ["男孩的", "nán hái de", "the boy's", "budak lelaki itu punya"],
    ["心", "xīn", "heart", "jantung / hati"],
    ["就像", "jiù xiàng", "just like", "seolah-olah"],
    ["发生了", "fā shēng le", "occurred", "berlaku"],
    ["强烈的", "qiáng liè de", "intense / strong", "hebat / kuat"],
    ["地震", "dì zhèn", "earthquake", "gempa bumi"],
    ["一般，", "yī bān", "as if / like", "sedemikian"],
    ["久久", "jiǔ jiǔ", "for a long time", "lama sekali"],
    ["无法", "wú fǎ", "unable to / cannot", "tidak mampu / tidak boleh"],
    ["平静。", "píng jìng", "calm down", "berasa tenang semula."],
    ["原来，", "yuán lái", "originally / turns out", "rupa-rupanya / asalnya"],
    ["阿姨", "ā yí", "Aunt", "Makcik"],
    ["自始至终", "zì shǐ zhì zhōng", "from beginning to end / all along", "dari awal hingga akhir / semenjak awal lagi"],
    ["都看穿了", "dōu kàn chuān le", "all saw through", "kesemuanya sudah nampak jelas / faham"],
    ["他的", "tā de", "his", "dia punya"],
    ["窘迫，", "jiǒng pò", "poverty / embarrassment / plight", "kesusahan hidup / kesempitan / kemaluan"],
    ["却用", "què yòng", "but using", "namun menggunakan"],
    ["这桶", "zhè tǒng", "this bucket", "tong... ini"],
    ["“温和的白漆”，", "wēn hé de bái qī", "gentle white paint", "cat putih yang lembut"],
    ["像一堵", "xiàng yì dǔ", "like a (wall)", "seperti sebuah"],
    ["无形的", "wú xíng de", "invisible / intangible", "yang ghaib / tidak kelihatan"],
    ["墙，", "qiáng", "wall", "dinding / tembok"],
    ["在冰冷的", "zài bīng lěng de", "in the ice-cold", "di dalam... yang sejuk beku"],
    ["世界里", "shì jiè lǐ", "world", "dunia"],
    ["温柔地", "wēn róu dì", "gently / tenderly", "dengan penuh kelembutan"],
    ["包裹住了", "bāo guǒ le", "wrapped up / embraced", "menyelubungi / membungkus rapat"],
    ["他的", "tā de", "his", "dia punya"],
    ["狼狈、", "láng bèi", "embarrassment", "keadaan kelam-kabut / aib"],
    ["难堪", "nán kān", "embarrassment / difficulty", "kemaluan / kesusahan"],
    ["与", "yǔ", "and", "dan"],
    ["罪过，", "zuì guò", "sin / fault / mistake", "kesalahan / dosa"],
    ["没有让", "méi yǒu ràng", "did not let", "tidak membiarkan"],
    ["任何", "rèn hé", "any", "sebarang"],
    ["鄙夷", "bǐ yí", "disdain / contempt", "pandangan hina / jijik"],
    ["和", "hé", "and", "dan"],
    ["惩罚", "chéng fá", "punishment / penalty", "hukuman / denda"],
    ["刺伤他", "cì shāng tā", "hurt him / sting him", "melukainya"],
    ["脆弱的", "cuì ruò de", "fragile / vulnerable", "yang rapuh / lemah"],
    ["自尊。", "zì zūn", "self-esteem / pride", "harga diri / maruah."],
    ["\n", "", "", ""],

    // --- 第8段 ---
    ["看着", "kàn zhe", "looking at", "memandang"],
    ["手中", "shǒu zhōng", "in the hand", "di dalam tangan"],
    ["那盒", "nà hé", "that box of", "sekotak... itu"],
    ["捂热了", "wǔ rè le", "warmed up", "menghangatkan / memanaskan"],
    ["他冰冷双手的", "tā bīng lěng shuāng shǒu de", "his icy cold hands", "dia punya sepasang tangan yang sejuk beku"],
    ["甜饼，", "tián bǐng", "cookies", "biskut manis"],
    ["两行", "liǎng háng", "two lines", "dua titisan"],
    ["温热的泪水，", "wēn rè de lèi shuǐ", "warm tears", "air mata yang hangat"],
    ["终于", "zhōng yú", "finally", "akhirnya"],
    ["从男孩", "cóng nán hái", "from the boy's", "daripada budak lelaki punya"],
    ["脸上", "liǎn shàng", "face", "wajah"],
    ["淌下来。", "tǎng xià lái", "streamed down.", "mengalir turun."],
    ["\n", "", "", ""],

    // --- 第9段 ---
    ["几天后，", "jǐ tiān hòu", "a few days later", "beberapa hari kemudian"],
    ["小杂货店的", "zá huò diàn de", "grocery store's", "kedai runcit kecil punya"],
    ["铁卷门", "tiě juǎn mén", "rolling iron door", "pintu besi gulung"],
    ["重新", "chóng xīn", "anew / again", "sekali lagi / semula"],
    ["变得", "biàn de", "became", "menjadi"],
    ["黄亮如金、", "huáng liàng rú jīn", "bright yellow like gold", "kuning berkilat bagai emas"],
    ["洁白如初。", "jié bái rú chū", "pure white as at first / spotlessly clean", "putih bersih seperti sediakala."],
    ["\n", "", "", ""],

    // --- 第10段 ---
    ["心中", "xīn zhōng", "in the heart", "di dalam hati"],
    ["有阳光，", "yǒu yáng guāng", "having sunshine", "ada cahaya matahari"],
    ["眼前", "yǎn qián", "in front of eyes", "di hadapan mata"],
    ["才会亮。", "cái huì liàng", "then will be bright", "baru akan cerah."],
    ["纯洁的", "chún jié de", "pure / clean", "yang suci / bersih"],
    ["思想，", "sī xiǎng", "thoughts / thinking", "pemikiran / minda"],
    ["可使", "kě shǐ", "can make", "boleh menyebabkan"],
    ["微小的", "wēi xiǎo de", "tiny / minute", "perbuatan kecil"],
    ["行动", "xíng dòng", "action / deed", "tindakan / amalan"],
    ["变得", "biàn de", "become", "menjadi"],
    ["高贵。", "gāo guì", "noble / lofty", "mulia / luhur."],
    ["善良", "shàn liáng", "kindness / goodness", "kebaikan / ketulusan"],
    ["从来不是", "cóng lái bú shì", "has never been", "semenjak awal bukanlah"],
    ["居高临下的", "jū gāo lín xià de", "condescending / high and mighty", "berada tinggi di atas / angkuh / sombong"],
    ["施舍", "shī shě", "alms / charity", "sedekah / belas iksan"],
    ["和", "hé", "and", "dan"],
    ["教训，", "jiào xùn", "lecture / lesson / scolding", "leteran / pengajaran / dendaan"],
    ["而是用", "ér shì yòng", "but rather using", "tetapi melainkan dengan menggunakan"],
    ["一种", "yì zhǒng", "a kind of", "sejenis / suatu"],
    ["充满尊严的", "chōng mǎn zūn yán de", "full of dignity / respect", "penuh maruah / kehormatan"],
    ["体面", "tǐ miàn", "dignity / face", "maruah / harga diri"],
    ["与", "yǔ", "and", "dan"],
    ["包容，", "bāo róng", "tolerance / inclusion / forgiveness", "toleransi / keampunan / sifat menerima"],
    ["去唤醒", "qù huàn xǐng", "to awaken / rouse", "untuk mengejutkan / menyedarkan"],
    ["另一个", "lìng yí gè", "another", "satu lagi punya"],
    ["迷失灵魂的、", "mí shī líng hún de", "lost soul's", "jiwa yang sesat punya"],
    ["那一桶", "nà yì tǒng", "that bucket of", "setong... itu"],
    ["无声的", "wú shēng de", "silent / voiceless", "yang tanpa suara / senyap"],
    ["白油漆。", "bái yóu qī", "white paint.", "cat putih."],
    ["\n", "", "", ""],

    // --- 作者落款 ---
    ["（佚名《深夜的黑油漆》，有改动）", "", "", ""]
];
